services:
    node:
        container_name: mini-crm-node
        image: 'node:lts-slim'
        working_dir: /home/node/app
        env_file:
            - .env
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm start'
        ports:
            - '5001:5001'
        volumes:
            - './back:/home/node/app'
        links:
            - mongo
    mongo:
        container_name: mini-crm-db
        image: mongo
        ports:
            - "27017:27017"
    react:
        container_name: mini-crm-react
        image: 'node:lts-slim'
        working_dir: /home/node/app
        command:
            - /bin/sh
            - '-c'
            - 'npm install && npm start'
        ports:
            - '3000:3000'
        volumes:
            - './front:/home/node/app'